modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
    modId="gastronomy"
    version="${file.jarVersion}"
    displayName="Gastronomy"
    authors="joshiejack"
    description='''Recipes, cooking and yummyness'''
[[dependencies.gastronomy]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.51,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gastronomy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gastronomy]]
    modId="penguinlib"
    mandatory=true
    versionRange="[0.5.0,)"
    ordering="NONE"
    side="BOTH"